Add start version backend
Antheso/bugtracker-backend pull request #1
Opened 2020-03-04 08:43 UTC by Kaskat

2020-03-04 09:54 UTC, Antheso commented on config/configuration.yml
> +database_host: "95.181.178.241"
К Р А С И В О

2020-03-04 09:54 UTC, Antheso commented on config/test_configuration.yml
> +database_host: "localhost"
Тоже выпилить

2020-03-04 09:54 UTC, Antheso commented on src/configuration.yml
> +database_password: "gEt0Q2sY"
Панимаю, выпилить

2020-03-04 09:54 UTC, Antheso commented on config/configuration.yml
> +database_host: "95.181.178.241"
Если он тебе нужен локально - просто добавь его в gitignore

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/DB/Query.java
> +        StringBuffer insertBuffer = new StringBuffer("INSERT INTO \"BugTracker\".\"Issue\"(summary, description, priority_id, status_id, project_id, assigne_id) VALUES(");
Сделай private функцию, в которую ты передаешь tableName, и которая вернет тебе StringBuffer insertBuffer, в который ты будешь append-ить все что тебе нужно. Поможет избежать дублирования кода в будущем. Нужно сделать 3 функции для RUD

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Authorization/Authorization.java
> +
многа отступов

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Authorization/AuthorizationDeserializer.java
> +//        User assignee = new User();
Нам нужен этот код?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Comment/Comment.java
> +    public Comment() {
зачем пустая функция?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Comment/Comment.java
> +    public Comment(String issueId, String text, String userId) {
Зачем эта функция?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Comment/CommentDao.java
> +        Statement stmt = null;
А зачем мы обнуляем? Мы можем сразу перезаписать? stmt = PostgreConnector.connection.createStatement();

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Comment/CommentDeserializer.java
> +        final String timestamp = node.get("timestamp").asText();
Это не текст а int

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Issue/Issue.java
> +//    @JsonInclude(NON_NULL)
Нам это нада?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Issue/Issue.java
> +    @JsonInclude(NON_NULL)
Задача может не иметь описания

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Issue/Issue.java
> +    public Issue() {
зачем пустая функция?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Issue/Issue.java
> +        this.project = project;
Нипанятна

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Issue/Issue.java
> +//    public String getNumber() {
Это нам нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Issue/Issue.java
> +    //constructor
Я вижу что конструктор))

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Issue/Issue.java
> +//    @Override
нам это нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Issue/Issue.java
> +    public Issue (int projectId) {
нипанятна зачем

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Issue/IssueDao.java
> +                //tempIssue.setNumber(number);
unused

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Issue/IssueDao.java
> +        Statement stmt = null;
тот же вопрос насчет перезаписи

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Issue/IssueDeserializer.java
> +//        final String projectName = node.get("project").get("projectName").asText();
Это нам нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Priority/Priority.java
> +    public Priority() {
У нас разве не может не быть конструктора? Короче выпили, если не нужен

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Project/Project.java
> +    public Project() {
Выпилить

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Status/Status.java
> +    public Status() {
Выпилить

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/Type/Type.java
> +    public Type() {
Выпилить

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/User/User.java
> +    public User(){
Если не нужен - выпилить

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/User/UserController.java
> +
многа отступов

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Entities/User/UserDao.java
> +            Statement stmt = PostgreConnector.connection.createStatement();
Сделать один statement и юзать его везде

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Javalin/AuthorizationController.java
> +        if (login.matches("[а-яА-ЯЄєІіїЇҐґ]+")) {
Бессмысленная проверка. Выше у тебя (я хз че тут по регекспам, опираюсь только на фразу "Login must contain only [a-z0-9_-].") проверка, которая уже прервет выполнение

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Javalin/AuthorizationController.java
> +//        final String password = new Hash(node.get("password").asText()).getHash();
Еще нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Javalin/AuthorizationController.java
> +    public AuthorizationController() {
Выпилить если не нужен

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Javalin/AuthorizationController.java
> +//    public static Handler validateToken = ctx -> {
Еще нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Javalin/AuthorizationController.java
> +//    public void CheckAuthorization(String login, String password)
Еще нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Javalin/JavalinManager.java
> +;
??

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Javalin/JavalinManager.java
> +    private JavalinManager(){}
Нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Javalin/JavalinManager.java
> +            put("admin", Roles.ADMIN);
Вообще эти значения должны храниться в БД, т.к. их опять же можно достать просто посмотрев реп, а это не ок

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Javalin/JavalinManager.java
> +//        new AuthorizationController();
Еще нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Javalin/JavalinManager.java
> +//        before(Filters.handleUserToken);
Еще нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Javalin/RouteController.java
> +
многа абзацов

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Main.java
> +            //config.addStaticFiles("/config");
еще нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Main.java
> +            //config.enableCorsForAllOrigins();
Еще нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Security/JWTAccessManager.java
> +        //permittedRoles.contains(role)
Еще нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Security/JWTAccessManager.java
> +            //context.redirect("/api/login");
Еще нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Security/UserProvider.java
> +//import app.Entities.User.User;
нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Security/UserProvider.java
> +                    .withClaim("roleId", "0"); //user.getRoleId()
//user.getRoleId() еще нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Security/UserProvider.java
> +        Algorithm algorithm = Algorithm.HMAC256("very_secret");
Algorithm algorithm = Algorithm.HMAC256("very_secret"); Лучший, секретно пизда. Вынести в конфиг

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Util/Filters.java
> +
Многа абзацов

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Util/Filters.java
> +        }else {
Отформатируй плез

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/Util/Path.java
> +        public static final String ISSUE = "/api" + "/issues";
Я бы вынес /api в переменную prefix например, и юзал ее

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/parser/JsonToObject.java
> +        //String json = readFile();
еще нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/parser/JsonToObject.java
> +        IssueList is = Is.readValue(new URL("file:src/test/resources/json_car.json"), IssueList.class);
Нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/parser/JsonToObject.java
> +        //IssueList is = Is.readValue(json, IssueList.class);
Нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/parser/JsonToObject.java
> +        FileUtils.readFileToString(new File(ObjectToJson.fileName), StandardCharsets.UTF_8);
Нужно?

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/parser/ObjectToJson.java
> +    static String fileName = "src/main/resources/json/main.json";
У тебя это не будет работать на серваке по идее

2020-03-04 09:54 UTC, Antheso commented on src/main/java/app/parser/ObjectToJson.java
> +    static String fileName = "src/main/resources/json/main.json";
Ну или будет, но будет писать не туда

2020-03-04 09:54 UTC, Antheso commented on src/main/resources/public/testIndex.html
> +    <meta name="description" content="The HTML5 Herald">
Еще нужен этот файл?

2020-03-04 09:54 UTC, Antheso commented on src/test/java/app/Util/ConfigurationTest.java
> +//    public void config() {
файл еще нужен?

2020-03-05 09:39 UTC, Kaskat commented on config/configuration.yml
> +database_host: "95.181.178.241"
Файл configuration.yml перемещён в target
Done

2020-03-05 09:39 UTC, Kaskat commented on config/test_configuration.yml
> +database_host: "localhost"
Файл test_configuration.yml перемещён в target
Done

2020-03-05 09:39 UTC, Kaskat commented on src/configuration.yml
> +database_password: "gEt0Q2sY"
Удалён
Done

2020-03-05 09:40 UTC, Kaskat commented on src/main/java/app/DB/Query.java
> +        StringBuffer insertBuffer = new StringBuffer("INSERT INTO \"BugTracker\".\"Issue\"(summary, description, priority_id, status_id, project_id, assigne_id) VALUES(");
Создал отдельные функции для создания StringBuffer
INSERT
UPDATE
DELETE

2020-03-05 09:40 UTC, Kaskat commented on src/main/java/app/Entities/Authorization/Authorization.java
> +
убрал

2020-03-05 09:40 UTC, Kaskat commented on src/main/java/app/parser/JsonToObject.java
> +        //IssueList is = Is.readValue(json, IssueList.class);
Удалено

2020-03-05 09:40 UTC, Kaskat commented on src/main/java/app/parser/JsonToObject.java
> +        FileUtils.readFileToString(new File(ObjectToJson.fileName), StandardCharsets.UTF_8);
Удалено

2020-03-05 09:40 UTC, Kaskat commented on src/main/java/app/parser/ObjectToJson.java
> +    static String fileName = "src/main/resources/json/main.json";
Удалено

2020-03-05 09:40 UTC, Kaskat commented on src/main/resources/public/testIndex.html
> +    <meta name="description" content="The HTML5 Herald">
Удалено

2020-03-05 09:40 UTC, Kaskat commented on src/test/java/app/Util/ConfigurationTest.java
> +//    public void config() {
Удалено

2020-03-05 09:43 UTC, Kaskat commented on src/main/java/app/Entities/Authorization/AuthorizationDeserializer.java
> +//        User assignee = new User();
Нам нужен этот код

2020-03-05 09:43 UTC, Kaskat commented on src/main/java/app/Entities/Comment/Comment.java
> +    public Comment() {
Пока нужна, позже выпилится

2020-03-05 09:45 UTC, Kaskat commented on src/main/java/app/Entities/Comment/Comment.java
> +    public Comment(String issueId, String text, String userId) {
Пересмотрю удалю лишний конструктор
видимо автогенерация произошла

2020-03-06 12:28 UTC, Antheso requested changes

2020-03-06 12:28 UTC, Antheso commented on src/main/java/app/Entities/Comment/CommentDao.java
>          Statement stmt = null;
Не убрал

2020-03-06 12:28 UTC, Antheso commented on src/main/java/app/Entities/Issue/IssueController.java
> +            ArrayList<Issue> data = IssueDao.getTableIssue();
Из фразы "Select issue failed" ты не поймешь что сломалось. Я бы пропихивал сюда exception

2020-03-06 12:28 UTC, Antheso commented on src/main/java/app/Entities/Issue/IssueDeserializer.java
> +//        final String authorId = node.get("author").get("authorId").asText();
А зачем закоментил? От лишних данных у меня ничего не сломается, только от недостатка)

2020-03-06 12:28 UTC, Antheso commented on src/main/java/app/Security/JWTAccessManager.java
> +        //permittedRoles.contains(role)
Видимо нужно

2020-03-06 12:28 UTC, Antheso commented on src/main/java/app/Security/JWTAccessManager.java
> +//        if (isAuthorized(context)) {
Если ты таким образом вырубаешь авторизацию, то по идее это не правильно, там у тебя на роуты должны вешаться middleware. Но да ладно, фиг с ним пока. Если я не прав и это лишнее - выпили)

2020-03-06 12:29 UTC, tanyalev reviewed
переименовать переменные в зависимости от хранимых значений; отформатировать код в едином стиле; убрать ненужные комментарии; пересмотреть код "подготавливающий" работу с дао

2020-03-06 12:29 UTC, tanyalev commented on LICENSE
> +   Copyright {yyyy} {name of copyright owner}
указать год и имя владельца лицензии

2020-03-06 12:29 UTC, tanyalev commented on pom.xml
> +    <artifactId>javalin-html-forms-example</artifactId>
изменить метаинформацию в мавене (описание проекта, версия java, название пакета, тип пакетирования)

2020-03-06 12:29 UTC, tanyalev commented on src/main/java/app/DB/PostgreConnector.java
> +            e.printStackTrace();
у нас есть логгирование? JUL или log4j

2020-03-06 12:29 UTC, tanyalev commented on src/main/java/app/DB/PostgreConnector.java
> +    static public Connection connection;
потоконебезопасный код, лучше в самом дао получать конешн по DataSource

2020-03-06 12:29 UTC, tanyalev commented on src/main/java/app/Entities/Authorization/AuthorizationDeserializer.java
> +        ObjectCodec oc = jsonParser.getCodec();
предлагаю `oc`заменить на `codec`

2020-03-06 12:29 UTC, tanyalev commented on src/main/java/app/Entities/Comment/CommentController.java
> +    public static Handler fetchAllComment = ctx -> {
предлагаю `ctx` заменить на `context` тут и далее

2020-03-06 12:29 UTC, tanyalev commented on src/main/java/app/Entities/Comment/CommentDao.java
> +            Statement stmt = PostgreConnector.connection.createStatement();
предлагаю заменить `stmt` на `statement` тут и далее.
предлагаю использование try-catch-with resources

2020-03-06 12:29 UTC, tanyalev commented on src/main/java/app/Entities/Issue/IssueDao.java
> +    public static void updateIssue
предлагаю определиться с форматированием кода

2020-03-06 12:29 UTC, tanyalev commented on src/main/java/app/Entities/Project/ProjectDao.java
> +                if(projectId == null && name == null)// bad way
комментарии говорят сами за себя. стоит переписать

2020-03-06 12:29 UTC, tanyalev commented on src/main/java/app/Util/Configuration.java
> +            Map<String, Object> obj = yaml.load(inputStream);
что такое obj?

2020-03-06 12:33 UTC, Antheso commented on src/main/java/app/Entities/Comment/CommentController.java
> +    public static Handler fetchAllComment = ctx -> {
Не вижу смысла, ctx довольно популярное сокращение слова context

2020-03-06 12:40 UTC, Antheso commented on src/main/java/app/Entities/Project/Project.java
> +    public Project() {
Плез)

2020-03-06 12:40 UTC, Antheso commented on src/main/java/app/Entities/Project/ProjectDao.java
> +                if(projectId == null && name == null)// bad way
+, ты уже где-то менял это на проверку isEmpty или типа того

2020-03-06 12:40 UTC, Antheso commented on src/main/java/app/Entities/Status/Status.java
> +    public Status() {
Плез

2020-03-06 12:40 UTC, Antheso commented on src/main/java/app/Entities/Status/StatusDao.java
> +                if(statusId == null && name == null)// bad way
Тоже поменяй проверку

2020-03-06 12:40 UTC, Antheso commented on src/main/java/app/Javalin/JavalinManager.java
> +            put("admin", Roles.ADMIN);
Решили что вернемся к этому позже

2020-03-06 12:40 UTC, Antheso commented on src/main/java/app/Javalin/AuthorizationController.java
> +        if (login.matches("[а-яА-ЯЄєІіїЇҐґ]+")) {
Ping

2020-03-06 12:40 UTC, Antheso commented on src/main/java/app/Security/UserProvider.java
> +//import app.Entities.User.User;
Ping

2020-03-06 12:40 UTC, Antheso commented on src/main/java/app/Security/UserProvider.java
> +                    .withClaim("roleId", "0"); //user.getRoleId()
Ping

2020-03-06 12:40 UTC, Antheso commented on src/main/java/app/Security/UserProvider.java
> +        Algorithm algorithm = Algorithm.HMAC256("very_secret");
Ну плез)

2020-03-06 12:40 UTC, Antheso commented on src/main/java/app/Util/Configuration.java
> +            Map<String, Object> obj = yaml.load(inputStream);
+1

2020-03-06 12:40 UTC, Antheso commented on src/main/java/app/Util/Path.java
> +        public static final String ISSUE = "/api" + "/issues";
ping

2020-03-06 13:02 UTC, tanyalev commented on src/main/java/app/Security/JWTAccessManager.java
>          if( d != null){
форматирование и переименовать `d`

2020-03-06 13:05 UTC, Antheso commented on src/main/java/app/Entities/Issue/Issue.java
> +    public Issue(){}
Выпилить

2020-03-06 15:56 UTC, tanyalev requested changes

2020-03-06 15:56 UTC, tanyalev commented on src/main/java/app/Javalin/JavalinManager.java
> +        db = new PostgreConnector();
тут у нас открывается статический (!) коннекшн (что потоконебезопасно, т.к. иногда может потребоваться уже заблокированый или используемый одновремменно) и не закрывается (!) ну я по крайней мере не вижу где он закрывается

именно поэтому я против использования синглтонных или нет фабрик коннекшенов. их необходимо открывать и закрывать (!) при создании запроса к бд с выключенным автокоммитом.

ссылки на хорошие примеры реализации дао в jdbc:
[официальная документация](https://docs.oracle.com/javase/tutorial/jdbc/basics/processingsqlstatements.html)
[сайт туториалов Jenkov](http://tutorials.jenkov.com/jdbc/connection.html) тут рекомендую весь цикл статей по этой теме, не только про коннекшн

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Entities/Comment/CommentDao.java
> +        Statement stmt = null;
Пересмотрю

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Entities/Comment/CommentDeserializer.java
> +        final String timestamp = node.get("timestamp").asText();
С бд получаю ответ в String
тебе нужно отправить ответ в String

Если инфа нужна для обработки, я бы её парсил ( но пока такого нет )

Ты считаешь лучше переводить?
bd -> String -> int -> String -> front

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Entities/Issue/IssueDao.java
> +                //tempIssue.setNumber(number);
Уберу)

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Entities/Issue/IssueDao.java
> +        Statement stmt = null;
Пересмотрю

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Entities/Issue/IssueDeserializer.java
> +//        final String projectName = node.get("project").get("projectName").asText();
Пока нет... уберу

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Entities/Priority/Priority.java
> +    public Priority() {
Уберём

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Entities/User/UserController.java
> +
уберём

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Javalin/AuthorizationController.java
> +        if (login.matches("[а-яА-ЯЄєІіїЇҐґ]+")) {
О, этого я не заметил. Сделаю ответ на фронт

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Javalin/JavalinManager.java
> +            put("admin", Roles.ADMIN);
Эксперементальная вещь, пока оставлю

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Security/JWTAccessManager.java
> +        //permittedRoles.contains(role)
еще нужно

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Security/UserProvider.java
> +//import app.Entities.User.User;
Уберём

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Security/UserProvider.java
> +                    .withClaim("roleId", "0"); //user.getRoleId()
Эксперементальная шутка, ещё нужна

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Security/UserProvider.java
> +        Algorithm algorithm = Algorithm.HMAC256("very_secret");
Вынесем, без выражений пожалуйста

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Util/Path.java
> +        public static final String ISSUE = "/api" + "/issues";
Переделаю

2020-03-06 21:51 UTC, Kaskat commented on src/main/java/app/Entities/Comment/CommentDao.java
>          Statement stmt = null;
Исправлено

2020-03-06 21:52 UTC, Kaskat commented on src/main/java/app/Entities/Issue/IssueController.java
> +            ArrayList<Issue> data = IssueDao.getTableIssue();
Select issue failed, уже как минимум намёк куда смотреть, и что сломалось
Пока не вижу другого обозначения

2020-03-06 21:52 UTC, Kaskat commented on src/main/java/app/Entities/Issue/IssueDeserializer.java
> +//        final String authorId = node.get("author").get("authorId").asText();
Исправлено

2020-03-06 21:55 UTC, Kaskat commented on src/main/java/app/Security/JWTAccessManager.java
> +//        if (isAuthorized(context)) {
Да это не правильно, этот код опережает сам себя
пока обозначим это экспериментальной функцией
в дальнейшем это понадобится

2020-03-06 21:57 UTC, Kaskat commented on LICENSE
> +   Copyright {yyyy} {name of copyright owner}
Исправлено на 2020 Team1

2020-03-06 21:59 UTC, Kaskat commented on pom.xml
> +    <artifactId>javalin-html-forms-example</artifactId>
Исправлено
artifactId - bugtracker-backend
version - 1.0
Остальные параметры по умолчанию

2020-03-06 22:00 UTC, Kaskat commented on src/main/java/app/DB/PostgreConnector.java
> +            e.printStackTrace();
Логирования нет

Нет опыта с JUL или log4j.

2020-03-06 22:02 UTC, Kaskat commented on src/main/java/app/Entities/Authorization/AuthorizationDeserializer.java
> +        ObjectCodec oc = jsonParser.getCodec();
Исправлено - codec

_____
Сам класс Authorization сейчас не используется.

2020-03-06 22:03 UTC, Kaskat commented on src/main/java/app/Entities/Comment/CommentController.java
> +    public static Handler fetchAllComment = ctx -> {
Оставил ctx

2020-03-06 22:04 UTC, Kaskat commented on src/main/java/app/Entities/Issue/IssueDao.java
> +    public static void updateIssue
Привёл к своему форматированию

2020-03-06 22:05 UTC, Kaskat commented on src/main/java/app/Entities/Comment/CommentDao.java
> +            Statement stmt = PostgreConnector.connection.createStatement();
Исправлено

2020-03-06 22:07 UTC, Kaskat commented on src/main/java/app/Util/Configuration.java
> +            Map<String, Object> obj = yaml.load(inputStream);
Тань, это твой код)

Поменял на configurationMap

2020-03-06 22:08 UTC, Kaskat commented on src/main/java/app/DB/PostgreConnector.java
> +    static public Connection connection;
Перед каждым запросом мы открываем connection
после мы его закрываем

2020-03-06 22:09 UTC, Kaskat commented on src/main/java/app/Entities/Project/ProjectDao.java
> +                if(projectId == null && name == null)// bad way
Исправлено

2020-03-06 22:09 UTC, Kaskat commented on src/main/java/app/Entities/Status/StatusDao.java
> +                if(statusId == null && name == null)// bad way
Исправлено

2020-03-06 22:10 UTC, Kaskat commented on src/main/java/app/Security/JWTAccessManager.java
>          if( d != null){
Исправлено

2020-03-06 22:10 UTC, Kaskat commented on src/main/java/app/Entities/Issue/Issue.java
> +    public Issue(){}
Исправлено

2020-03-06 22:23 UTC, Kaskat commented on src/main/java/app/Javalin/JavalinManager.java
> +        db = new PostgreConnector();
я понял о чем ты
Сейчас я добавил открытие и закрытие для каждого запроса

2020-03-06 22:24 UTC, Kaskat commented on src/main/java/app/Javalin/JavalinManager.java
> +        db = new PostgreConnector();
Но мой подход мне уже не по душе, нужно придумать способ подключать и отключать получше

2020-03-07 08:59 UTC, Antheso commented on src/main/java/app/Entities/Comment/CommentDeserializer.java
> +        final String timestamp = node.get("timestamp").asText();
Прикол в том что это поле изначально в бд добавляю я, т.к. я шлю тебе в комменте этот timestamp. И я шлю тебе его в number))

2020-03-07 09:01 UTC, tanyalev commented on src/main/java/app/Javalin/JavalinManager.java
> +        db = new PostgreConnector();
> Но мой подход мне уже не по душе, нужно придумать способ подключать и отключать получше

я скинула ссылки на примеры того как это делают хорошим способом, ты ведь ознакомился, да?

2020-03-07 09:03 UTC, tanyalev commented on src/main/java/app/Entities/Comment/CommentDao.java
> +                PostgreConnector.endConnection();
а что если сюда зайдут 2 потока, а статический коннекшн у нас 1?

2020-03-07 09:05 UTC, Antheso commented on src/main/java/app/Entities/Issue/IssueController.java
> +            ArrayList<Issue> data = IssueDao.getTableIssue();
Окей, up 2 you

2020-03-07 09:05 UTC, Antheso commented on src/main/java/app/Security/JWTAccessManager.java
> +//        if (isAuthorized(context)) {
Окей

2020-03-07 09:17 UTC, Antheso requested changes

2020-03-07 09:17 UTC, Antheso commented on src/main/java/app/Entities/Comment/CommentDeserializer.java
> +        final String timestamp = node.get("timestamp").asText();
Вообщем надо пообщаться будет по этому поводу, пока пускай string

2020-03-07 09:17 UTC, Antheso commented on src/main/java/app/Util/Configuration.java
> +        String relatePath = PostgreConnector.class.getProtectionDomain().getCodeSource().getLocation().getPath();
Вообще убери возможность передавать path в конструктор (конфиг лежит у нас в одном месте), и сделай его singleton т.к. на данный момент ты 2 раза считываешь один и тот же файл

2020-03-07 09:40 UTC, tanyalev commented on src/main/java/app/DB/PostgreConnector.java
> +            e.printStackTrace();
плохо, хотелось бы в случае внезапного падения на демонстрации узнать что случилось (

2020-03-07 15:30 UTC, Kaskat commented on src/main/java/app/Util/Configuration.java
> +        String relatePath = PostgreConnector.class.getProtectionDomain().getCodeSource().getLocation().getPath();
Переделал
Теперь считываем файл единожды перед стартом Javalin

значение Path теперь внутри Configuration в виде String

2020-03-07 15:31 UTC, Kaskat commented on src/main/java/app/Entities/Comment/CommentDao.java
> +                PostgreConnector.endConnection();
Переделал
Теперь перед каждым запросом мы создаём коннекшн и удаляем при выходе

2020-03-07 15:32 UTC, Kaskat commented on src/main/java/app/Javalin/JavalinManager.java
> +        db = new PostgreConnector();
Да, я посмотрел, спасибо за доки) 
Теперь получше

2020-03-07 16:35 UTC, Kaskat commented on src/main/java/app/DB/PostgreConnector.java
> +//            connection.setAutoCommit(false);
Пока отключим
как только придумаем как применить, подключу или удалю

2020-03-07 16:35 UTC, Kaskat commented on src/main/java/app/Entities/Issue/IssueDeserializer.java
> +//        final String authorName = node.get("author").get("name").asText();
Это место падает, т.к. сейчас фронт не присылает мне Автора

2020-03-07 16:38 UTC, Antheso approved these changes

2020-03-07 16:54 UTC, tanyalev requested changes

2020-03-07 16:54 UTC, tanyalev commented on src/main/java/app/Entities/Comment/CommentDao.java
> +                comments.add(new Comment(user_id, text));
```
if (!StringUtil.isEmpty(user_id) && !StringUtil.isEmpty(text)) {
    comments.add(new Comment(user_id, text));
}
```
и не нужен `continue`

2020-03-07 16:54 UTC, tanyalev commented on src/main/java/app/Entities/Issue/Issue.java
> +    public Issue (ResultSet resultSet)
мне не нравится такой конструктор, лучше вызывать тот который выше в самом дао

2020-03-07 16:54 UTC, tanyalev commented on src/main/java/app/Entities/Issue/IssueController.java
> +            }else throw new Exception("Insert issue failed");
пожалуйста, давайте использовать нормальное форматирование в java, не надо тут C#, C++ с gnu и windows стайл, только джава, а то тут такое там такое, там вообще нет фигурных скобочек..

2020-03-07 16:54 UTC, tanyalev commented on src/main/java/app/Entities/Issue/IssueDao.java
> +                    continue;
опять же, пляски с `continue`

2020-03-07 16:54 UTC, tanyalev commented on src/main/java/app/Entities/Priority/PriorityDao.java
> +                    continue;
continuing using `continue`?)

2020-03-07 16:54 UTC, tanyalev commented on src/main/java/app/Security/JWTAccessManager.java
> +        return false;
```
return Objects.nonNull(tokenStorage.get(jwt.getToken()));
```
ну или
```
return tokenStorage.get(jwt.getToken()) != null;
```

2020-03-07 17:33 UTC, Kaskat commented on src/main/java/app/Entities/Comment/CommentDao.java
> +                comments.add(new Comment(user_id, text));
Согласен, улетело куча кода, continue уже не нужно

2020-03-07 17:34 UTC, Kaskat commented on src/main/java/app/Entities/Issue/Issue.java
> +    public Issue (ResultSet resultSet)
Не понял что выше...
____

Поменял конструктор

2020-03-07 17:35 UTC, Kaskat commented on src/main/java/app/Entities/Issue/IssueController.java
> +            }else throw new Exception("Insert issue failed");
На досуге как-нибудь

Сорри не джавист

2020-03-07 17:37 UTC, Kaskat commented on src/main/java/app/Security/JWTAccessManager.java
> +        return false;
С токенами еще будет веселье 
понимаю что это примитивно, зато наглядно
______
Мне не сложно поменяю и это..)

2020-03-07 18:05 UTC, tanyalev approved these changes
пора двигаться дальше

2020-03-07 18:14 UTC, merged